Icinga/icingadb-web

application/controllers/TacticalController.php, configuration.php, library/Icingadb/Common/BaseFilter.php, library/Icingadb/Compat/UrlMigrator.php, library/Icingadb/Widget/HostSummaryDonut.php, library/Icingadb/Widget/ServiceSummaryDonut.php, public/css/module.less, public/css/widgets.less
=> Add Tactical Overview

library/Icingadb/Widget/BaseHostListItem.php, library/Icingadb/Widget/BaseItemList.php, library/Icingadb/Widget/BaseListItem.php, library/Icingadb/Widget/BaseServiceListItem.php, library/Icingadb/Widget/DowntimeList.php, library/Icingadb/Widget/HostList.php, library/Icingadb/Widget/ItemList/BaseCommentListItem.php, library/Icingadb/Widget/ItemList/BaseDowntimeListItem.php, library/Icingadb/Widget/ItemList/CommentList.php, library/Icingadb/Widget/ServiceList.php, public/js/action-list.js
=> Fix active list item handling

application/controllers/HistoryController.php, application/controllers/HostController.php, application/controllers/ServiceController.php, library/Icingadb/Model/AcknowledgementHistory.php, library/Icingadb/Model/History.php, library/Icingadb/Widget/ItemList/HistoryListItem.php
=> Fix missing style for ack history entries

application/controllers/ErrorController.php, application/forms/DatabaseConfigForm.php, library/Icingadb/Common/Database.php, library/Icingadb/Common/IcingaRedis.php, library/Icingadb/Web/Controller.php
=> Fix configuration defaults

library/Icingadb/Widget/Detail/CheckStatistics.php, library/Icingadb/Widget/Detail/DowntimeCard.php
=> Fix floating point locale awareness

library/Icingadb/Common/MarkdownText.php, library/Icingadb/Widget/Detail/CommentDetail.php, library/Icingadb/Widget/Detail/DowntimeDetail.php, library/Icingadb/Widget/Detail/ObjectDetail.php, library/Icingadb/Widget/ItemList/BaseDowntimeListItem.php, library/Icingadb/Widget/ItemList/HistoryListItem.php, library/Icingadb/Widget/ItemList/NotificationListItem.php, public/css/module.less
=> Fix markdown not rendered everywhere

library/Icingadb/Compat/CompatHost.php, library/Icingadb/Compat/CompatObject.php, library/Icingadb/Compat/CompatService.php, library/Icingadb/Widget/Detail/ObjectDetail.php
=> Fix incompatible hook usage with 3rd party modules

library/Icingadb/Widget/CheckAttempt.php
=> Fix error on string format in history view

application/forms/RedisConfigForm.php, configuration.php, library/Icingadb/Setup/ApiTransportPage.php, library/Icingadb/Setup/ApiTransportStep.php, library/Icingadb/Setup/DbResourcePage.php, library/Icingadb/Setup/DbResourceStep.php, library/Icingadb/Setup/IcingaDbWizard.php, library/Icingadb/Setup/RedisPage.php, library/Icingadb/Setup/RedisStep.php, library/Icingadb/Setup/WelcomePage.php, module.info
=> Setup integration

application/controllers/HostController.php, application/controllers/ServiceController.php
=> Fix broken history list of flapping objects

library/Icingadb/Setup/IcingaDbWizard.php
=> IcingaDbWizard: Enable the ipl module automatically

library/Icingadb/Widget/ItemList/HistoryListItem.php
=> HistoryListItem: Fix title for state change

library/Icingadb/Model/CommentHistory.php, library/Icingadb/Model/DowntimeHistory.php, library/Icingadb/Widget/ItemList/HistoryListItem.php
If the same user who created it removes it:
If it's a different user:
=> Show who removed a comment, downtime or acknowledgement

application/controllers/HostgroupsController.php, application/controllers/HostsController.php, application/controllers/ServicegroupsController.php, application/controllers/ServicesController.php, configuration.php, library/Icingadb/Web/Controller.php, library/Icingadb/Widget/FilterControl.php
=> Add missing search and dashboard integration

library/Icingadb/Common/ServiceLink.php, public/css/lists.less
=> Fix missing gap between comment badges

library/Icingadb/Widget/Detail/CustomVarTable.php, library/Icingadb/Widget/Detail/ObjectDetail.php
=> Fix non collapsible containers

public/css/lists.less
=> lists.less: Fix downtime-list caption ellipsisizing

library/Icingadb/Widget/FilterControl.php
=> Fix hosts without services not found in tactical overview

library/Icingadb/Widget/HostSummaryDonut.php, library/Icingadb/Widget/ServiceSummaryDonut.php, public/css/widgets.less
=> Add summary in tactical overview

public/css/widgets.less
=> Fix squished health view in narrow viewports

public/css/widgets.less
=> Let checkstatistics line look like in chrome as in other browsers

public/css/widgets.less
=> Don't allow bubble titles to wrap

library/Icingadb/Model/AcknowledgementHistory.php, library/Icingadb/Model/ActionUrl.php, library/Icingadb/Model/Checkcommand.php, library/Icingadb/Model/CheckcommandArgument.php, library/Icingadb/Model/CheckcommandEnvvar.php, library/Icingadb/Model/CommentHistory.php, library/Icingadb/Model/DowntimeHistory.php, library/Icingadb/Model/Endpoint.php, library/Icingadb/Model/Environment.php, library/Icingadb/Model/Eventcommand.php, library/Icingadb/Model/EventcommandArgument.php, library/Icingadb/Model/EventcommandEnvvar.php, library/Icingadb/Model/FlappingHistory.php, library/Icingadb/Model/History.php, library/Icingadb/Model/HostState.php, library/Icingadb/Model/IconImage.php, library/Icingadb/Model/NotesUrl.php, library/Icingadb/Model/Notification.php, library/Icingadb/Model/NotificationHistory.php, library/Icingadb/Model/Notificationcommand.php, library/Icingadb/Model/NotificationcommandArgument.php, library/Icingadb/Model/NotificationcommandEnvvar.php, library/Icingadb/Model/ServiceState.php, library/Icingadb/Model/StateHistory.php, library/Icingadb/Model/Timeperiod.php, library/Icingadb/Model/TimeperiodRange.php, library/Icingadb/Model/Zone.php
Ensures a user will get suggestions in the search for them.
=> Add remaining meta data to all important models

library/Icingadb/Model/Behavior/Bitmask.php, library/Icingadb/Model/Behavior/FlattenedObjectVars.php, library/Icingadb/Model/Behavior/ReRoute.php, library/Icingadb/Web/Control/SearchBar/ObjectSuggestions.php, library/Icingadb/Web/Controller.php
blocked by https://github.com/Icinga/ipl-stdlib/pull/20
=> Utilize native filter meta data instead of properties

application/controllers/CommentsController.php, application/controllers/DowntimesController.php, application/controllers/HistoryController.php, application/controllers/HostgroupsController.php, application/controllers/HostsController.php, application/controllers/NotificationsController.php, application/controllers/ServicegroupsController.php, application/controllers/ServicesController.php, application/controllers/TacticalController.php, application/controllers/UsergroupsController.php, application/controllers/UsersController.php, library/Icingadb/Web/Controller.php, library/Icingadb/Widget/ViewModeSwitcher.php, public/css/common.less
refs https://github.com/Icinga/icingaweb2/issues/4094
=> Utilize ipl SearchEditor

library/Icingadb/Common/Auth.php, library/Icingadb/Web/Control/SearchBar/ObjectSuggestions.php
This, is based on https://github.com/Icinga/ipl-orm/pull/13. Some references to it slipped into master already due to various merges. Though these changed now (again) and have to be removed. And added again. (differently)
I hope it's finished now...
=> Cleanup filter optimization hints

library/Icingadb/ProvidedHook/X509/Sni.php, run.php
The hook X509/Sni is implemented for icingadb in this commit.
=> Introduce implementation for hook X509/Sni in icingadb

library/Icingadb/Compat/CompatService.php, library/Icingadb/Widget/Detail/ObjectDetail.php, public/css/widget/actions.less
=> Fix action and note url labels

library/Icingadb/Web/Controller.php
blocked by https://github.com/Icinga/ipl-web/pull/19
fixes #129
=> Ensure to apply the user's default limit

application/controllers/HostController.php, application/controllers/ServiceController.php, configuration.php, library/Icingadb/Command/IcingaApiCommand.php, library/Icingadb/Command/Object/GetObjectCommand.php, library/Icingadb/Command/Renderer/IcingaApiCommandRenderer.php, library/Icingadb/Command/Transport/ApiCommandTransport.php, library/Icingadb/Command/Transport/CommandTransport.php, library/Icingadb/Common/Links.php, library/Icingadb/Common/ObjectInspectionDetail.php, library/Icingadb/Widget/Detail/HostInspectionDetail.php, library/Icingadb/Widget/Detail/ServiceInspectionDetail.php, public/css/common.less, public/css/widget/object-inspection.less
Includes Icinga 2 API results and Icinga Redis results
resolves #117
resolves #181
=> Add object inspection

application/controllers/HostController.php, library/Icingadb/Widget/Detail/HostMetaInfo.php, public/css/common.less, public/css/widget/host-meta-info.less
fixes #55
refs https://github.com/Icinga/icingaweb2/issues/4098
=> Add missing host info

library/Icingadb/ProvidedHook/IcingaHealth.php, library/Icingadb/ProvidedHook/RedisHealth.php, run.php
refs https://github.com/Icinga/icingaweb2/pull/4355
=> Add health hooks

public/css/list/downtime-list.less, public/css/list/item-list.less
=> CSS: Display 5 lines of caption in .downtime-list.detailed

library/Icingadb/Common/DetailActions.php, public/css/common.less, public/js/action-list.js
=> Action-List: Add selected items to the bottom status-bars

library/Icingadb/Widget/ViewModeSwitcher.php
Tool tip to ViewModeSwitcher has been added here.
#144
=> Add tool tip to ViewModeSwitcher.

application/forms/Command/Object/AcknowledgeProblemForm.php, application/forms/Command/Object/AddCommentForm.php, application/forms/Command/Object/ProcessCheckResultForm.php, application/forms/Command/Object/ScheduleCheckForm.php, application/forms/Command/Object/ScheduleServiceDowntimeForm.php, application/forms/Command/Object/SendCustomNotificationForm.php, library/Icingadb/Common/BaseTableRowItem.php, library/Icingadb/Common/ObjectInspectionDetail.php, library/Icingadb/Common/ServiceLink.php, library/Icingadb/Setup/ApiTransportStep.php, library/Icingadb/Setup/DbResourceStep.php, library/Icingadb/Setup/RedisStep.php, library/Icingadb/Web/Control/SearchBar/ObjectSuggestions.php, library/Icingadb/Widget/BaseHostListItem.php, library/Icingadb/Widget/BaseServiceListItem.php, library/Icingadb/Widget/Detail/HostMetaInfo.php, library/Icingadb/Widget/Detail/ObjectDetail.php, library/Icingadb/Widget/HostListItemDetailed.php, library/Icingadb/Widget/HostSummaryDonut.php, library/Icingadb/Widget/ItemList/BaseCommentListItem.php, library/Icingadb/Widget/ItemList/BaseDowntimeListItem.php, library/Icingadb/Widget/ItemList/CommandTransportListItem.php, library/Icingadb/Widget/ItemList/HostgroupListItem.php, library/Icingadb/Widget/ItemList/ServicegroupListItem.php, library/Icingadb/Widget/ItemList/UserListItem.php, library/Icingadb/Widget/ItemList/UsergroupListItem.php, library/Icingadb/Widget/PerfDataTable.php, library/Icingadb/Widget/ServiceListItemDetailed.php, library/Icingadb/Widget/ServiceSummaryDonut.php, library/Icingadb/Widget/ViewModeSwitcher.php
Requires https://github.com/Icinga/ipl-html/pull/51
=> Use strict ipl-html interfaces

configuration.php
resolves #59
This uses the new icons in icingadb dashboard.
=> configuration: Replace default icons in dashboard

library/Icingadb/Model/HostState.php, library/Icingadb/Model/ServiceState.php, library/Icingadb/Model/State.php, library/Icingadb/Util/PerfData.php, library/Icingadb/Util/PerfDataFormat.php, library/Icingadb/Widget/Detail/ObjectDetail.php, library/Icingadb/Widget/HostListItemDetailed.php, library/Icingadb/Widget/ServiceListItemDetailed.php
=> Perfdata: Add support for more UoMs

application/forms/Command/Object/ScheduleHostDowntimeForm.php, application/forms/Command/Object/ScheduleServiceDowntimeForm.php
[hostdowntime_end_fixed], [hostdowntime_end_flexible], [hostdowntime_flexible_duration], [servicedowntime_end_fixed], [servicedwontime_end_flexible],
[servicedowntime_flexible_duration] and [comment_text] options added to [settings] section in config.ini file used in  host/service downtime dialog.
icinga/icingaweb2#4364
=> Add end time and comment options to settings section for host/service downtime dialog

application/controllers/CommentsController.php, application/controllers/DowntimesController.php, application/controllers/HostController.php, application/controllers/HostgroupsController.php, application/controllers/HostsController.php, application/controllers/NotificationsController.php, application/controllers/ServiceController.php, application/controllers/ServicegroupsController.php, application/controllers/ServicesController.php, library/Icingadb/Common/HostLinks.php, library/Icingadb/Common/ServiceLinks.php, library/Icingadb/Widget/Detail/ObjectDetail.php, library/Icingadb/Widget/ShowMore.php
Removes:
* `icingadb/host/comments`
* `icingadb/host/downtimes`
* `icingadb/service/comments`
* `icingadb/service/downtimes`
=> Drop redundant routes

library/Icingadb/Widget/ShowMore.php, public/css/common.less, public/css/list/comment-list.less, public/css/list/downtime-list.less, public/css/list/item-list.less, public/css/list/item-table.less, public/css/list/list-item.less, public/css/list/user-list.less, public/css/widget/host-meta-info.less, public/css/widget/object-statistics.less, public/css/widget/quick-actions.less, public/css/widget/view-mode-switcher.less
The alignment should now works for all views.
fixes #130
fixes #131
fixes #132
fixes #133
fixes #141
closes #185
=> Align all controls on the same baseline

application/controllers/ServicesController.php, application/views/scripts/joystickPagination-icingadb.phtml, application/views/scripts/services/grid-flipped.phtml, application/views/scripts/services/grid.phtml, configuration.php, library/Icingadb/Data/PivotTable.php, library/Icingadb/Web/Control/ProblemToggle.php, public/css/common.less, public/css/view/service-grid.less
=> Add Service Grid

library/Icingadb/Widget/Detail/HostDetail.php, library/Icingadb/Widget/Detail/ObjectDetail.php
=> Remove redudant titles

library/Icingadb/Widget/ItemList/BaseDowntimeListItem.php, public/css/list/item-list.less
'for' is the most natural sounding according to Andrew.
fixes #213
=> Optimize downtime list item titles

application/controllers/UserController.php, application/controllers/UsergroupController.php, library/Icingadb/Common/Links.php, library/Icingadb/Widget/Detail/UserDetail.php, library/Icingadb/Widget/Detail/UsergroupDetail.php
=> display user and usergroups customvars

public/css/common.less
=> CSS: Apply the separation line to the list footer element

library/Icingadb/Common/ObjectInspectionDetail.php
=> Bugfix ObjectInspectionDetail::formatTimestamp()

application/controllers/HostController.php, application/controllers/HostsController.php, application/controllers/ServiceController.php, application/controllers/ServicesController.php, library/Icingadb/Widget/BaseItemList.php, library/Icingadb/Widget/BaseListItem.php, library/Icingadb/Widget/StateList.php, library/Icingadb/Widget/StateListItem.php, public/css/list/item-list.less, public/css/list/list-item.less
I created this as a draft PR.
You might want to check the implementation so far, @nilmerg.
resolves #79
=> Add icon image support

application/controllers/CommentsController.php, application/controllers/DowntimesController.php, application/controllers/HostgroupController.php, application/controllers/HostsController.php, application/controllers/ServicegroupController.php, application/controllers/ServicesController.php, library/Icingadb/Web/Controller.php
=> Feature: Increase limit on minimal view mode

library/Icingadb/Model/State.php, library/Icingadb/Model/StateHistory.php, library/Icingadb/Widget/Detail/CheckStatistics.php, library/Icingadb/Widget/Detail/EventDetail.php, public/css/widget/check-statistics.less
=> Add scheduling source to the footer of check statistics

application/controllers/HostgroupController.php, application/controllers/ServicegroupController.php
=> Fix unknown column error in host service group details

library/Icingadb/Web/Controller.php
=> Controller: Fix missing `name` when switching view mode

application/controllers/HistoryController.php, application/controllers/HostController.php, application/controllers/NotificationsController.php, library/Icingadb/Web/Controller.php
=> Controller: Fix uncaught argument count error

application/controllers/HostgroupController.php, application/controllers/ServicegroupController.php, library/Icingadb/Model/Comment.php
=> Fix host service group detail cannot open with last comment

library/Icingadb/Common/LoadMore.php
=> LoadMore: Don't reset page number on view mode change

doc/02-Installation.md, library/Icingadb/Common/BaseItemList.php, library/Icingadb/Web/Controller.php, library/Icingadb/Widget/Detail/ObjectDetail.php, library/Icingadb/Widget/ItemList/StateListItem.php, public/css/list/item-table.less, public/css/list/list-item.less
=> Fix PDF export capability

library/Icingadb/Setup/ApiTransportStep.php
=> `ApiTransportStep`: Fix commandtransport config not setup correctly

application/controllers/HostController.php, application/controllers/ServiceController.php
=> Support `ViewModeSwitcher` & `sortControl` in `Host/Service` history

application/controllers/ServicesController.php, application/views/scripts/services/grid-flipped.phtml, application/views/scripts/services/grid.phtml, library/Icingadb/Web/Control/ProblemToggle.php
=> Fix that searching in servicegrid has no effect

application/controllers/HostController.php
=> HostController: Add `sortControl` to services tab of host detail

application/views/scripts/services/grid-flipped.phtml, application/views/scripts/services/grid.phtml, library/Icingadb/Common/LoadMore.php, public/css/list/item-table.less
=> Add `No items found` to controllers

library/Icingadb/Widget/Detail/EventDetail.php
=> EventDetail: Fix improper notification detail wording

public/js/action-list.js
=> Set active state on list items after page refresh

application/controllers/HostController.php, application/controllers/ServiceController.php
=> Make object header unclickable in detail view

application/controllers/NotificationsController.php
=> NotificationsCotroller: Remove autorefresh to improve performance

library/Icingadb/Common/ObjectInspectionDetail.php, library/Icingadb/Widget/Detail/CommentDetail.php, library/Icingadb/Widget/Detail/DowntimeDetail.php, library/Icingadb/Widget/Detail/EventDetail.php, library/Icingadb/Widget/Detail/ObjectDetail.php, library/Icingadb/Widget/Detail/UserDetail.php, library/Icingadb/Widget/Detail/UsergroupDetail.php, public/css/common.less
=> Apply general detail styles with a single class

library/Icingadb/Web/Controller.php
=> Link preferred view mode with the current view

public/js/action-list.js
=> Unselect the correct object

public/css/list/item-list.less
=> Fix the alignment of the control separator of the columns

application/controllers/CommandTransportController.php, application/forms/Command/Instance/ToggleInstanceFeaturesForm.php, application/forms/Command/Object/AcknowledgeProblemForm.php, application/forms/Command/Object/AddCommentForm.php, application/forms/Command/Object/DeleteCommentForm.php, application/forms/Command/Object/DeleteDowntimeForm.php, application/forms/Command/Object/ProcessCheckResultForm.php, application/forms/Command/Object/RemoveAcknowledgementForm.php, application/forms/Command/Object/ScheduleCheckForm.php, application/forms/Command/Object/ScheduleHostDowntimeForm.php, application/forms/Command/Object/ScheduleServiceDowntimeForm.php, application/forms/Command/Object/SendCustomNotificationForm.php, application/forms/Command/Object/ToggleObjectFeaturesForm.php
=> Show a notification for every successful action

library/Icingadb/Widget/Detail/DowntimeCard.php
=> Fix progress bar bubble title for downtime starting in the future

library/Icingadb/Common/BaseListItem.php, library/Icingadb/Widget/ItemList/BaseCommentListItem.php, library/Icingadb/Widget/ItemList/BaseDowntimeListItem.php, library/Icingadb/Widget/ItemList/BaseHistoryListItem.php, library/Icingadb/Widget/ItemList/BaseNotificationListItem.php, library/Icingadb/Widget/ItemList/CommandTransportListItem.php, library/Icingadb/Widget/ItemList/HistoryList.php, library/Icingadb/Widget/ItemList/HostgroupList.php, library/Icingadb/Widget/ItemList/HostgroupListItem.php, library/Icingadb/Widget/ItemList/NotificationList.php, library/Icingadb/Widget/ItemList/ServicegroupList.php, library/Icingadb/Widget/ItemList/ServicegroupListItem.php, library/Icingadb/Widget/ItemList/UserList.php, library/Icingadb/Widget/ItemList/UserListItem.php, library/Icingadb/Widget/ItemList/UsergroupList.php, library/Icingadb/Widget/ItemList/UsergroupListItem.php
=> Set active state on list items after refresh

public/css/common.less
=> Fix `search-editor-opener` alignment

library/Icingadb/Widget/Detail/UserDetail.php, library/Icingadb/Widget/ItemList/UserListItem.php
=> UserDetail: Enhance user detail view

application/forms/Command/Object/DeleteDowntimeForm.php, library/Icingadb/Model/Downtime.php, public/css/widget/cancel-button.less
=> Don't allow user to delete scheduled downtimes

application/forms/RedisConfigForm.php, library/Icingadb/Common/IcingaRedis.php, library/Icingadb/Common/ObjectInspectionDetail.php, library/Icingadb/Model/Behavior/VolatileState.php, library/Icingadb/ProvidedHook/ApplicationState.php, library/Icingadb/ProvidedHook/RedisHealth.php, library/Icingadb/Setup/RedisPage.php
=> Fix multiple redis connection attempts

application/controllers/HistoryController.php, application/controllers/HostController.php, application/controllers/NotificationsController.php, application/controllers/ServiceController.php, library/Icingadb/Web/Controller.php
=> Fix view mode switching shows less items when using vertical pagination

public/css/common.less
=> Extend the width of the action list in the detail view

library/Icingadb/Web/Controller.php, public/css/common.less
requires https://github.com/Icinga/ipl-web/pull/42
=> Fix `ContinueWith` usage

library/Icingadb/Common/ObjectInspectionDetail.php, library/Icingadb/Widget/Detail/CustomVarTable.php, library/Icingadb/Widget/Detail/DowntimeDetail.php, library/Icingadb/Widget/Detail/EventDetail.php, library/Icingadb/Widget/Detail/HostMetaInfo.php, library/Icingadb/Widget/Detail/PerfDataTable.php, library/Icingadb/Widget/Detail/UserDetail.php
=> Better declare empty values

library/Icingadb/Model/State.php, library/Icingadb/Model/StateHistory.php
=> Remove `scheduling_source` placeholder

application/controllers/HostController.php, application/controllers/ServiceController.php, library/Icingadb/Widget/ItemList/BaseHistoryListItem.php, library/Icingadb/Widget/ItemList/HostDetailHeader.php, library/Icingadb/Widget/ItemList/HostList.php, library/Icingadb/Widget/ItemList/HostListItemDetailed.php, library/Icingadb/Widget/ItemList/ServiceDetailHeader.php, library/Icingadb/Widget/ItemList/ServiceList.php, library/Icingadb/Widget/ItemList/ServiceListItemDetailed.php, library/Icingadb/Widget/StateChange.php, public/css/widget/state-change.less
=> Add missing status details

doc/04-Security.md, library/Icingadb/Common/Auth.php, library/Icingadb/Model/Behavior/ReRoute.php, library/Icingadb/Model/Host.php, library/Icingadb/Model/Service.php, library/Icingadb/Web/Control/SearchBar/ObjectSuggestions.php
requires https://github.com/Icinga/ipl-orm/pull/22
resolves #384
=> Allow `host.user.name` and `host.usergroup.name` as well as `service...` in restrictions

library/Icingadb/Widget/Detail/EventDetail.php
=> Use EventDetailExtentionHook in EventDetail

library/Icingadb/Widget/Detail/CheckStatistics.php, library/Icingadb/Widget/Detail/DowntimeCard.php, public/css/mixin/progress-bar.less, public/css/widget/check-statistics.less
=> Fix downtime progress bar bubble overflow

application/controllers/ServicesController.php
=> Add service id and host ids gridcols to pivotTable

public/css/common.less
ref https://github.com/Icinga/ipl-web/pull/52
=> common.less: Add margin-bottom to `.search-suggestions` class

public/css/common.less, public/css/list/action-list.less, public/css/list/downtime-list.less, public/css/list/item-list.less, public/css/list/item-table.less, public/css/list/list-item.less, public/css/markdown.less, public/css/mixin/progress-bar.less, public/css/view/service-grid.less, public/css/widget/actions.less, public/css/widget/cancel-button.less, public/css/widget/check-attempt.less, public/css/widget/check-statistics.less, public/css/widget/comment-popup.less, public/css/widget/downtime-card.less, public/css/widget/migrate-popup.less, public/css/widget/monitoring-health.less, public/css/widget/object-features.less, public/css/widget/object-meta-info.less, public/css/widget/object-statistics.less, public/css/widget/performance-data-table.less, public/css/widget/quick-actions.less, public/css/widget/state-badge.less, public/css/widget/state-change.less, public/css/widget/tag-list.less, public/css/widget/view-mode-switcher.less
=> Use css variables for colors

public/css/widget/migrate-popup.less
=> Redesign migrate popup

public/css/common.less, public/css/mixin/progress-bar.less, public/css/mixin/state-badges.less, public/css/widget/object-meta-info.less, public/css/widget/performance-data-table.less, public/css/widget/state-badge.less, public/css/widget/state-change.less
=> Fix theme issues

application/forms/Command/Object/ToggleObjectFeaturesForm.php
=> Display a proper success message when toggling object passive checks

library/Icingadb/Command/Object/ProcessCheckResultCommand.php, library/Icingadb/Command/Transport/ApiCommandTransport.php, library/Icingadb/Command/Transport/CommandTransport.php, library/Icingadb/Common/HostStates.php, library/Icingadb/Common/ObjectInspectionDetail.php, library/Icingadb/Common/ServiceStates.php, library/Icingadb/ProvidedHook/IcingaHealth.php, library/Icingadb/Web/Navigation/Renderer/ProblemsBadge.php, library/Icingadb/Widget/Detail/CheckStatistics.php, library/Icingadb/Widget/Detail/HostDetail.php, library/Icingadb/Widget/Detail/ServiceDetail.php, library/Icingadb/Widget/ItemList/BaseHistoryListItem.php, library/Icingadb/Widget/ItemList/StateListItem.php
Consolidation of fixes for issues resulting from #363
fixes #420
=> Return type fixes

configuration.php, library/Icingadb/Web/Navigation/Renderer/ProblemsBadge.php
createBadge() can return null if there are no problems. However,
the new code that decides whether or not to create a link did not
check it.
=> Don't fail if the problems badge is null

library/Icingadb/Web/Controller.php
=> Controller: Only keep preserved params for the searchbar action

configuration.php
=> configuration.php: Add missing description for icingadb overview

application/forms/Command/Object/ToggleObjectFeaturesForm.php
=> Set default value of mixed type feature commands of multi-selected hosts or services to "noop".

library/Icingadb/Common/StateBadges.php, library/Icingadb/Widget/HostStateBadges.php, library/Icingadb/Widget/ServiceStateBadges.php
=> Fix incorrect filter columns in list footers

application/views/scripts/services/grid-flipped.phtml, application/views/scripts/services/grid.phtml
=> Fix incorrect assignment of class handled to the service badges in service grid.

application/controllers/ServicesController.php
The x- and y-axis column headers and sort control in service grid must use display names for hosts and services.
fix #453
=> Use display names as axis headers for hosts and services in service grid.

library/Icingadb/Widget/Detail/ObjectDetail.php
Previously, host notification recipients also included notification recipients from their services.
=> Fix too extensive host notification recipients

library/Icingadb/Widget/ItemList/StateListItem.php
=> Use font-awesome icons if icon_image exists without extension

library/Icingadb/Widget/Detail/CommentDetail.php
=> Fix incorrect description in comment detail

library/Icingadb/Common/ObjectInspectionDetail.php, library/Icingadb/Widget/ItemList/BaseDowntimeListItem.php
=> Fix locale dependend float conversion to string

library/Icingadb/Web/Navigation/IcingadbHostAction.php, library/Icingadb/Web/Navigation/IcingadbServiceAction.php, public/css/common.less, public/css/list/comment-list.less
=> comment-list: Add missing space before "on" in title

library/Icingadb/Widget/Detail/PerfDataTable.php
=> PerfDataTable: Don't double encode cell values

library/Icingadb/Util/PerfData.php, library/Icingadb/Util/PerfDataSet.php
=> Fix that invalid perfdata breaks detail views

library/Icingadb/Common/DetailActions.php, public/js/action-list.js
=> Fix active row state persistency

application/controllers/ServiceController.php
=> Fix duplicate service history entries

public/js/action-list.js
=> Fix that target _blank links in list items are loaded by XHR

library/Icingadb/Web/Navigation/Renderer/HostProblemsBadge.php, library/Icingadb/Web/Navigation/Renderer/ProblemsBadge.php, library/Icingadb/Web/Navigation/Renderer/ServiceProblemsBadge.php
=> Show hints for problem badges for Hosts and Services in nav bar

library/Icingadb/Web/Control/ViewModeSwitcher.php
=> Fix view mode switcher shows different mode than what is used

library/Icingadb/Util/PerfData.php
refs https://github.com/Icinga/icinga2/issues/9206
=> PerfData: Render unkown UOMs as-is

application/controllers/HostController.php, application/controllers/HostgroupController.php, application/controllers/ServiceController.php, application/controllers/ServicegroupController.php, application/controllers/UserController.php, application/controllers/UsergroupController.php, library/Icingadb/Widget/Detail/CommentDetail.php, library/Icingadb/Widget/Detail/DowntimeDetail.php, library/Icingadb/Widget/Detail/HostDetail.php, library/Icingadb/Widget/Detail/ObjectDetail.php, library/Icingadb/Widget/Detail/ServiceDetail.php, library/Icingadb/Widget/Detail/UserDetail.php, library/Icingadb/Widget/Detail/UsergroupDetail.php, public/css/common.less
=> Add missing details in exported detail views

application/controllers/CommandTransportController.php, application/controllers/CommentController.php, application/controllers/CommentsController.php, application/controllers/DowntimeController.php, application/controllers/DowntimesController.php, application/controllers/EventController.php, application/controllers/HealthController.php, application/controllers/HistoryController.php, application/controllers/HostController.php, application/controllers/HostgroupController.php, application/controllers/HostgroupsController.php, application/controllers/HostsController.php, application/controllers/NotificationsController.php, application/controllers/ServiceController.php, application/controllers/ServicegroupController.php, application/controllers/ServicegroupsController.php, application/controllers/ServicesController.php, application/controllers/TacticalController.php, application/controllers/UserController.php, application/controllers/UsergroupController.php, application/controllers/UsergroupsController.php, application/controllers/UsersController.php
refs https://github.com/Icinga/ipl-web/pull/72
=> Adjust calls to `CompatController::setTitle()`

library/Icingadb/Common/SearchControls.php, library/Icingadb/Web/Controller.php
requires https://github.com/Icinga/ipl-web/pull/69
=> Introduce `Icinga\Module\Icingadb\Common\SearchControls`

library/Icingadb/Authentication/ObjectAuthorization.php
=> Fix that command refusals don't override grants

library/Icingadb/Common/ObjectInspectionDetail.php, library/Icingadb/Model/HostState.php, library/Icingadb/Model/ServiceState.php, library/Icingadb/Model/State.php, library/Icingadb/Widget/ItemList/BaseHistoryListItem.php, library/Icingadb/Widget/ItemList/HostDetailHeader.php, library/Icingadb/Widget/ItemList/ServiceDetailHeader.php, library/Icingadb/Widget/ItemList/StateListItem.php, library/Icingadb/Widget/StateChange.php, public/css/common.less, public/css/widget/state-change.less
=> Utilize `previous_soft_state` column

library/Icingadb/Common/Auth.php
Forces the given restriction/filter to be wrapped in a subquery if there is a restriction applied
to `*/services` or `*/hosts` with `hostgroup.name` or `servicegroup.name`. If `hostgroup.name` is
used for services restriction, it is automatically wrapped to a subquery, because service model
has no direct relation to `hostgroup` and it is the same with host model and `servicegroup.name`.
fixes #514
=> Auth: Force query optimization on union queries

library/Icingadb/Model/ActionUrl.php, library/Icingadb/Model/Host.php, library/Icingadb/Model/IconImage.php, library/Icingadb/Model/NotesUrl.php, library/Icingadb/Model/Service.php
refs https://github.com/Icinga/icingadb/pull/460
=> Fix some primary key irregularities

library/Icingadb/Web/Controller.php
ref https://github.com/Icinga/icingaweb2/pull/4765
=> Controller: Don't set store key because it is no longer required

library/Icingadb/Model/Customvar.php, library/Icingadb/Model/Host.php, library/Icingadb/Model/Service.php, test/php/library/Icingadb/Common/MacrosTest.php
=> Model: Implement `createDefaults` where applicable

library/Icingadb/Util/ObjectSuggestionsCursor.php, library/Icingadb/Util/PerfData.php, library/Icingadb/Widget/ItemList/BaseDowntimeListItem.php
=> Fix PHP 8.1 related bugs

application/controllers/HostgroupController.php, application/controllers/ServicegroupController.php, library/Icingadb/Redis/VolatileStateResults.php, library/Icingadb/Widget/ItemList/StateList.php, library/Icingadb/Widget/Notice.php, public/css/common.less, public/css/widget/notice.less
=> Handle redis errors gracefully

.mailmap
and not sometimes as "Alexander Aleksandrovič Klimov <alexander.klimov@icinga.com>" to deduplicate myself in AUTHORS.
=> .mailmap: display me always as "Alexander A. Klimov <alexander.klimov@icinga.com>"

library/Icingadb/Widget/Detail/CheckStatistics.php
=> CheckStatistics: Add EmptyState

library/Icingadb/Widget/ItemList/BaseHistoryListItem.php
=> Show correct flapping event details

library/Icingadb/Widget/Detail/EventDetail.php, library/Icingadb/Widget/ItemList/BaseHistoryListItem.php
=> Fix acknowledgements registered before icingadb history recording

library/Icingadb/Compat/UrlMigrator.php
=> UrlMigrator: Lower filter values targeting enum types

application/controllers/HistoryController.php, application/controllers/NotificationsController.php
Currently, the load more urls are fixed and hence the filters are not preserved after clicking on load more.
In this fix load more url has been changed dynamically upon applying filters for history or notifications and
hence preserving the filters.
fixes #590
=> Preserve filters after clicking `Load More`

application/controllers/CommentsController.php, application/controllers/DowntimesController.php, application/controllers/HostgroupsController.php, application/controllers/HostsController.php, application/controllers/ServicegroupsController.php, application/controllers/ServicesController.php
=> Drop `view` param from show more urls in all index routes

library/Icingadb/Compat/CompatObject.php, library/Icingadb/Widget/Detail/ObjectDetail.php
=> Fix legacy hook integration

library/Icingadb/Widget/ItemList/StateListItem.php
=> StateListItem: Also don't show last state change if its zero

library/Icingadb/Common/ObjectInspectionDetail.php
=> ObjectInspectionDetail: Handle formatting errors gracefully

application/controllers/HostgroupsController.php, application/controllers/ServicegroupsController.php, library/Icingadb/Web/Control/SearchBar/ObjectSuggestions.php, library/Icingadb/Web/Controller.php
=> Fix incorrect hostgroup/servicegroup detail results

application/controllers/ServicesController.php, application/controllers/TacticalController.php, configuration.php, library/Icingadb/Model/ServicestateSummary.php, library/Icingadb/Web/Controller.php
=> Fix incomplete search results

library/Icingadb/Model/Behavior/ReRoute.php, library/Icingadb/Model/Comment.php, library/Icingadb/Model/Downtime.php, library/Icingadb/Model/History.php, library/Icingadb/Model/NotificationHistory.php
=> Auth: Apply objects filter with `servicegroup.name` correctly

library/Icingadb/Authentication/ObjectAuthorization.php, library/Icingadb/Widget/Detail/EventDetail.php, library/Icingadb/Widget/ItemList/BaseHistoryListItem.php, library/Icingadb/Widget/ItemList/BaseNotificationListItem.php
=> Fix broken history if config is not synced yet

application/controllers/CommentController.php, application/controllers/EventController.php, library/Icingadb/Common/TicketLinks.php, library/Icingadb/Widget/Detail/CommentDetail.php, library/Icingadb/Widget/Detail/EventDetail.php, library/Icingadb/Widget/Detail/ObjectDetail.php, library/Icingadb/Widget/ItemList/BaseCommentListItem.php, library/Icingadb/Widget/ItemList/BaseDowntimeListItem.php, library/Icingadb/Widget/ItemList/BaseHistoryListItem.php, library/Icingadb/Widget/ItemList/CommentList.php, library/Icingadb/Widget/ItemList/DowntimeList.php, library/Icingadb/Widget/ItemList/HistoryList.php
=> Provide generic tts integration

library/Icingadb/Widget/Detail/ObjectDetail.php
=> ObjectDetail: Fix action and note url retrieval

public/js/action-list.js
=> action-list.js: Open subject links in a new window if requested

library/Icingadb/Util/PluginOutput.php, library/Icingadb/Widget/Detail/EventDetail.php, library/Icingadb/Widget/ItemList/BaseHistoryListItem.php, library/Icingadb/Widget/ItemList/BaseNotificationListItem.php
=> Fix output not rendered yet

library/Icingadb/Widget/Detail/CommentDetail.php, library/Icingadb/Widget/Detail/DowntimeDetail.php
=> Fix that some comments cannot be deleted

application/forms/RedisConfigForm.php
=> RedisConfigForm: Properly clear empty sections/options

public/css/list/list-item.less
=> CSS: Fix list item footer colors

configuration.php
=> Properly populate sidebar and dashboard if monitoring is installed but not accessible

library/Icingadb/Hook/IcingadbSupportHook.php
=> Fix that modules don't use icingadb as backend if monitoring is inaccessible

application/controllers/MigrateController.php
=> Fix that the migration widget is still visible even if only icingadb is accessible

public/css/list/list-item.less
=> list-item.less: Do not show the comment popup transparently

application/controllers/ConfigController.php
=> ConfigController: Always check if the user has permissions

application/forms/Command/Object/AcknowledgeProblemForm.php, application/forms/Command/Object/AddCommentForm.php
=> AcknowledgeProblemForm: Don't show datepicker if `expire` checkbox is unchecked

library/Icingadb/Compat/CompatHost.php, library/Icingadb/Compat/CompatService.php
=> Fix that repeated grafana graphs are not shown properly

public/js/action-list.js
=> Fix that the dashboard loses selection

library/Icingadb/Widget/Detail/CheckStatistics.php
=> CheckStatistics: Show `retry_interval` if object in `problem && soft_state`

application/controllers/CommentsController.php, application/controllers/DowntimesController.php, application/controllers/HostsController.php, application/controllers/ServicesController.php, application/controllers/TacticalController.php, application/controllers/UsergroupsController.php, application/controllers/UsersController.php, library/Icingadb/Model/Host.php, library/Icingadb/Model/Hostgroup.php, library/Icingadb/Model/Service.php, library/Icingadb/Model/Servicegroup.php, library/Icingadb/Model/User.php, library/Icingadb/Model/Usergroup.php, library/Icingadb/Web/Controller.php
=> Enhance global search

library/Icingadb/ProvidedHook/CreateHostSlaReport.php, library/Icingadb/ProvidedHook/CreateServiceSlaReport.php, run.php
=> Add reporting hooks to DetailsAction

library/Icingadb/Model/NotificationHistory.php, library/Icingadb/Web/Control/SearchBar/ObjectSuggestions.php
=> Filter for notification command

application/forms/Command/Object/AcknowledgeProblemForm.php, application/forms/Command/Object/AddCommentForm.php
=> (AddComment/AcknowledgeProblem)Form: Add validators to `expire_time` element

application/forms/Command/Object/ScheduleServiceDowntimeForm.php
fixes #765
Blocked by: Icinga/ipl-html#122
=> Don't allow creating downtimes with flexible duration `0h0m`

library/Icingadb/Widget/Detail/CheckStatistics.php, public/css/widget/check-statistics.less
=> Fix negative next check value when both active and passive checks are disabled

library/Icingadb/ProvidedHook/Reporting/SlaReport.php
resolves: Icinga/icingadb-web#770
=> SlaReport: Breakdown into an hour view

library/Icingadb/Hook/Common/TotalSlaReportUtils.php, library/Icingadb/ProvidedHook/Reporting/TotalHostSlaReport.php, library/Icingadb/ProvidedHook/Reporting/TotalServiceSlaReport.php, run.php
resolves: Icinga/icingadb-web#771
=> Introduce Total Host and Total Service SLA Report

configuration.php, library/Icingadb/Widget/Detail/CheckStatistics.php, library/Icingadb/Widget/Detail/DowntimeCard.php, library/Icingadb/Widget/Detail/HostMetaInfo.php, library/Icingadb/Widget/ItemList/BaseDowntimeListItem.php, library/Icingadb/Widget/ItemList/StateListItem.php, public/css/common.less, public/css/list/downtime-list.less, public/css/mixin/progress-bar.less, public/css/widget/check-statistics.less, public/css/widget/downtime-card.less, public/js/progress-bar.js
resolves #493
blocked by https://github.com/Icinga/ipl-web/pull/160
refs https://github.com/Icinga/ipl-web/pull/161
refs https://github.com/Icinga/icingaweb2/pull/5044
=> Visualize that a check or downtime is running

library/Icingadb/ProvidedHook/CreateHostSlaReport.php, library/Icingadb/ProvidedHook/CreateHostsSlaReport.php, library/Icingadb/ProvidedHook/CreateServiceSlaReport.php, library/Icingadb/ProvidedHook/CreateServicesSlaReport.php, run.php
=> Provide reporting hook for single host/service

library/Icingadb/Widget/ItemList/HostListItemDetailed.php, library/Icingadb/Widget/ItemList/ServiceListItemDetailed.php, public/css/list/list-item.less
=> Fix `list-item` footer

library/Icingadb/Common/StateBadges.php, library/Icingadb/Web/Navigation/Renderer/ProblemsBadge.php, library/Icingadb/Widget/HostStateBadges.php, library/Icingadb/Widget/ServiceStateBadges.php, library/Icingadb/Widget/StateBadge.php, public/css/mixin/state-badges.less, public/css/widget/state-badge.less, test/php/library/Icingadb/Common/StateBadgesTest.php
Removing and transferring them to ipl-web was a mistake and not thought through. ipl-icinga could be an alternative location, but that's only theory right now.
ref #474
=> Restore `StateBadge` and `StateBadges`

library/Icingadb/Compat/UrlMigrator.php
=> UrlMigrator: Strip leading slashes from url paths to check

library/Icingadb/Common/IcingaRedis.php, library/Icingadb/Redis/VolatileStateResults.php
..as well as `isUnavailable`. Transferred from `VolatileStateResults` to be re-used outside of it.
=> IcingaRedis: Introduce `fetchHostState` and `fetchServiceState`..

application/forms/Command/Object/AcknowledgeProblemForm.php, application/forms/Command/Object/AddCommentForm.php, application/forms/Command/Object/ProcessCheckResultForm.php, application/forms/Command/Object/RemoveAcknowledgementForm.php, application/forms/Command/Object/ScheduleCheckForm.php, application/forms/Command/Object/SendCustomNotificationForm.php
..a command has been transmitted for.
requires https://github.com/Icinga/ipl-stdlib/pull/49
=> Use `ipl\Stdlib\iterable_value_first` to access the first item..

application/forms/RedisConfigForm.php, library/Icingadb/Setup/ApiTransportPage.php, library/Icingadb/Setup/IcingaDbWizard.php
requires https://github.com/Icinga/icingaweb2/pull/5094
=> IcingaDbWizard: Fix requirements

library/Icingadb/ProvidedHook/X509/Sni.php
=> Allow to reset active db connection

phpstan-baseline.neon
IPL orm has received a lot of updates that make these ignore patterns obsolete.
=> Update phpstan baseline config

library/Icingadb/Web/Controller.php
=> Controller: Preserve only selected search request parameters

library/Icingadb/Widget/Detail/ObjectDetail.php, phpstan-baseline.neon
=> ObjectDetail: Don't try to group the user query if it's not there

library/Icingadb/Common/CommandActions.php
=> CommandActions: Only respond with JSON if it's an API request

library/Icingadb/Web/Navigation/Action.php
=> Fix broken detail due to duplicate actions

library/Icingadb/Web/Navigation/Renderer/ProblemsBadge.php
=> Fix missing badge in problems menu

library/Icingadb/Model/Hostgroupsummary.php, library/Icingadb/Model/ServicegroupSummary.php
=> Fix broken host and servicegroup quick search

configuration.php
=> Fix that the global search ignores route denylists

library/Icingadb/Widget/ItemList/HostDetailHeader.php, library/Icingadb/Widget/ItemList/ServiceDetailHeader.php, library/Icingadb/Widget/ItemList/StateListItem.php, library/Icingadb/Widget/ItemTable/StateRowItem.php, phpstan-baseline-standard.neon
=> Do not show okay states as handled if the object is unreachable

application/controllers/UserController.php, library/Icingadb/Model/User.php, library/Icingadb/Widget/Detail/UserDetail.php
fixes https://github.com/Icinga/icingadb-web/issues/1010
=> UserDetail: add missing information

library/Icingadb/Setup/DbResourcePage.php
=> DbResourcePage: Avoid showing a default charset for pgsql

public/css/widget/object-header.less
I've copied some of this from #1104
=> Fix redundancy group header alignment

library/Icingadb/Model/Host.php, library/Icingadb/Model/Service.php
This PR fixes a small typo in Model/Host and Model/Service
=> Fix typo in Model/Host and Model/Service

application/views/scripts/services/grid-flipped.phtml
=> Fix detail view links for services in flipped grid

library/Icingadb/Widget/Detail/DowntimeCard.php, public/css/mixin/progress-bar.less, public/css/widget/check-statistics.less
=> Fix horizontal scroll-bar in object detail view

library/Icingadb/Hook/ExtensionHook/ObjectDetailExtensionHook.php, library/Icingadb/Hook/ExtensionHook/ObjectsDetailExtensionHook.php, library/Icingadb/Widget/Detail/ObjectDetail.php
=> Fix that detail extensions produce gaps

library/Icingadb/Common/IcingaRedis.php, module.info
=> Predis: Use the newly introduced xread command/method

library/Icingadb/Widget/Detail/ObjectDetail.php
=> ObjectDetail: Properly format last_state_change for PDF

application/controllers/CommentsController.php, application/controllers/ContactgroupsController.php, application/controllers/ContactsController.php, application/controllers/DowntimesController.php, application/controllers/HostController.php, application/controllers/HostgroupController.php, application/controllers/HostgroupsController.php, application/controllers/HostsController.php, application/controllers/RedundancygroupController.php, application/controllers/ServiceController.php, application/controllers/ServicegroupController.php, application/controllers/ServicegroupsController.php, application/controllers/ServicesController.php, library/Icingadb/Widget/ItemList/ObjectList.php
requires https://github.com/Icinga/ipl-web/pull/276
=> Controllers: Use `paginationControl::getEmptyStateMessage()` to set list's message

library/Icingadb/Widget/ItemTable/StateItemTable.php
fixes https://github.com/Icinga/icingadb-web/issues/1182
=> StateItemTable: Add missing property `$emptyStateMessage` and getter/setter

application/forms/RedisConfigForm.php, library/Icingadb/Common/IcingaRedis.php
=> Add support for redis acl/username and database selection

public/css/item/item-layout.less
Minor improvements to the item layout.
=> Ellipsize plugin output in list items with common layout

library/Icingadb/Widget/Detail/CustomVarTable.php
=> CustomVarTable: Let the user fully collapse subgroups

library/Icingadb/Common/StateBadges.php
=> StateBadges: Actually render links for single badges

public/css/item/redundancy-group.less
=> css: Make sure redundancy group statistics fit

library/Icingadb/Model/Instance.php, library/Icingadb/ProvidedHook/IcingaHealth.php, library/Icingadb/ProvidedHook/RedisHealth.php, library/Icingadb/Widget/Health.php
=> Show Icinga DB and Redis version in health

library/Icingadb/Widget/Detail/RedundancyGroupDetail.php
fixes https://github.com/Icinga/icingadb-web/issues/1240
=> RedundancyGroupDetail: Eliminate duplicate nodes

library/Icingadb/Model/Host.php, library/Icingadb/Model/Service.php
=> Add missing `unreachable_parent` relation
