application/controllers/HostController.php, application/controllers/ServiceController.php, library/Icingadb/Widget/Detail/HostDetail.php, library/Icingadb/Widget/Detail/HostStatistics.php, library/Icingadb/Widget/Detail/ObjectDetail.php, library/Icingadb/Widget/Detail/ObjectStatistics.php, library/Icingadb/Widget/Detail/ServiceDetail.php, library/Icingadb/Widget/Detail/ServiceStatistics.php, library/Icingadb/Widget/ItemList/HostgroupListItem.php, library/Icingadb/Widget/ItemList/ServicegroupListItem.php, public/css/lists.less, public/css/widgets.less
The widget as it's used to display service statistics in a host's details:
The same is now used in hostgroup- and servicegroup-list items.
Requires https://github.com/Icinga/ipl-html/pull/25
=> Object statistics

application/controllers/ServicesController.php, library/Icingadb/Common/HostStates.php, library/Icingadb/Common/ServiceStates.php, library/Icingadb/Model/Hostgroupsummary.php, library/Icingadb/Model/HoststateSummary.php, library/Icingadb/Model/ServicegroupSummary.php, library/Icingadb/Model/ServicestateSummary.php, library/Icingadb/Widget/Detail/CheckStatistics.php, library/Icingadb/Widget/StateListItem.php, public/css/module.less
In case Icinga DB did not synchronize the state yet, we now show this to the user properly.
=> Fix wrong state information

library/Icingadb/ProvidedHook/ApplicationState.php
It works now this way:
* Icinga DB hearbeat N/A => Icinga DB outage
* Icinga DB heartbeat outdated but newer than Icinga Redis heartbeat => Icinga Redis outage
* Icinga DB heartbeat outdated but older than Icinga Redis heartbeat => Icinga DB outage
fixes #41
=> Fix incorrect icingadb redis outage detection

public/css/lists.less
The font sizes of list item output preview in the original monitoring module is a little smaller than in the current module.
I thought it would be a bad idea since it makes the eye focus more on the headings. and looks a little cleaner.
=> lists.less: Adjust caption font size for list-items

application/controllers/CommentsController.php, application/controllers/DowntimesController.php, application/forms/Command/Instance/ToggleInstanceFeaturesForm.php, application/forms/Command/Object/AcknowledgeProblemForm.php, application/forms/Command/Object/AddCommentForm.php, application/forms/Command/Object/CheckNowForm.php, application/forms/Command/Object/DeleteCommentForm.php, application/forms/Command/Object/DeleteDowntimeForm.php, application/forms/Command/Object/ProcessCheckResultForm.php, application/forms/Command/Object/RemoveAcknowledgementForm.php, application/forms/Command/Object/ScheduleCheckForm.php, application/forms/Command/Object/ScheduleHostDowntimeForm.php, application/forms/Command/Object/ScheduleServiceDowntimeForm.php, application/forms/Command/Object/SendCustomNotificationForm.php, application/forms/Command/Object/ToggleObjectFeaturesForm.php, configuration.php, library/Icingadb/Authentication/ObjectAuthorization.php, library/Icingadb/Common/Auth.php, library/Icingadb/Common/CommandActions.php, library/Icingadb/Widget/Detail/CommentDetail.php, library/Icingadb/Widget/Detail/DowntimeDetail.php, library/Icingadb/Widget/Detail/MultiselectQuickActions.php, library/Icingadb/Widget/Detail/QuickActions.php
Permissions and restrictions from the very same role are now tied together. That means the permissions of a role won't apply to objects that are available due to another role.
refs https://github.com/Icinga/icingaweb2/issues/2455
=> Object permissions

library/Icingadb/Widget/Detail/HostMetaInfo.php
To avoid that users misinterpret the host detail labels as filter columns.
=> HostMetaInfo: Add dots instead of underscores

application/controllers/CommentController.php, application/controllers/DowntimeController.php, application/controllers/EventController.php, application/controllers/HostController.php, application/controllers/HostgroupController.php, application/controllers/ServiceController.php, application/controllers/ServicegroupController.php, application/controllers/UserController.php, application/controllers/UsergroupController.php
Parameters used to identify what will be shown need to be preserved. Just like it's done for filters in lists.
refs #299
refs #312
=> Don't shift URL params to identify objects in detail views

library/Icingadb/Widget/Detail/DowntimeDetail.php
=> Properly display start_time and end_time of downtimes if they are NULL

library/Icingadb/Web/Controller.php
The problem here was all the parameters added by the search-bar could never be deleted again as
the tactical overview doesn't provide any preserved params that could reset this filter.
This PR fixes that by simply removing all parameters from the URL being redirected when the trash icon is pressed.
resolves #318
=> Controller: Reset all params on form change

public/css/common.less
The searchbar suggestions are overlapped by the footer. To fix this either the controls need a higher z-index or the footer gets his removed.
I opted for removing the footer's z-index. I cannot see a reason why it's necessary. It's never positioned and so doesn't need to be elevated.
I tested it on Chrome and Firefox. The box shadow is visible there, that's the only reason I thought why a z-index might be needed.
=> css: Remove z-index from footer

library/Icingadb/Widget/ItemList/StateListItem.php
=> Add default path to icon img if no relative path has been specified

library/Icingadb/Common/Macros.php
Let's say we have `$host.hostgroup$` as a macro. In the do while loop our first and last column/property is `hostgroup`. But we check at the beginning only if `$value` isn't of these types `Query, ResultSet, Array` and then defeeferencing `$value->hostgroup` after which `$properties` is going to be empty and the type checks will never be executed for the second time.
=> Macros: Fix return type mismatch

public/css/widget/state-change.less
This fixes the horizontal alignment of the smaller soft state state balls.
=> CSS: Align state-change soft-state-balls

configuration.php, library/Icingadb/Web/Navigation/Renderer/ProblemsBadge.php, library/Icingadb/Web/Navigation/Renderer/TotalProblemsBadge.php, public/css/widget/state-badge.less
When monitoring module is disabled instead of showing host and service details in Icinga DB menu, the details needs to be distributed in Overview, Problems and History menus respectively.
This is to imitate the case when only monitoring module is active.
fix #394
=> Add Overview, Problems and History menu when monitoring module is disabled

library/Icingadb/Command/Transport/ApiCommandTransport.php
Using null results in an argument type error.
=> Use the empty string for probing the Icinga 2 API

application/controllers/HostController.php
service_state now also has the host_id column, so we need to
qualify host_id with a table name in the WHERE condition.
This is a preparation for Icinga/icingadb#403, and can already be merged.
=> Fix Column 'host_id' in where clause is ambiguous

library/Icingadb/Model/Checkcommand.php, library/Icingadb/Model/CheckcommandArgument.php, library/Icingadb/Model/CheckcommandCustomvar.php, library/Icingadb/Model/CheckcommandEnvvar.php, library/Icingadb/Model/Eventcommand.php, library/Icingadb/Model/EventcommandArgument.php, library/Icingadb/Model/EventcommandCustomvar.php, library/Icingadb/Model/EventcommandEnvvar.php, library/Icingadb/Model/Notification.php, library/Icingadb/Model/Notificationcommand.php, library/Icingadb/Model/NotificationcommandArgument.php, library/Icingadb/Model/NotificationcommandCustomvar.php, library/Icingadb/Model/NotificationcommandEnvvar.php
This PR implements schema changes to the command reference IDs (Added {check,notification,event} prefix to command_id columns)
Icinga DB PR: https://github.com/Icinga/icingadb/pull/385
Affected relations:
- {check,notitication,event}command: envvar, argument, customvar
I wasn't quite sure how to test those relations, but found that it's enough to get an empty result while using the search bar to show that the relation is working. Broken relations would result in a "Relation not found" error.
- Argument: http://10.211.55.8/icingaweb2/icingadb/services?service.checkcommand.argument.description
- Envvar: http://10.211.55.8/icingaweb2/icingadb/services?service.checkcommand.envvar.envvar_key
- Customvar: http://10.211.55.8/icingaweb2/icingadb/services?service.checkcommand.customvar.name
- …
=> Implement schema command_id prefix change

application/forms/Command/Object/ToggleObjectFeaturesForm.php
In case of elements other than CheckboxElement $element->getValue() must be used instead of $element->isChecked().
fix #440
=> Fix dis/enabling of feature commands of multi-selected hosts or services.

library/Icingadb/Hook/IcingadbSupportHook.php
Rename method  `isSetAsBackend()` to `isIcingaDbSetAsPreferredBackend()`
=> IcingadbSupportHook: Rename method to `isIcingaDbSetAsPreferredBackend()`

application/controllers/CommentsController.php, application/controllers/DowntimesController.php, application/controllers/HistoryController.php, application/controllers/HostController.php, application/controllers/HostsController.php, application/controllers/ServiceController.php, application/controllers/ServicesController.php, library/Icingadb/Model/Downtime.php
=> Optimize queries

configuration.php
When you try to load module related css or less files via cli command, like I did today,
this configuration script is executed and you will get this error message
=> Fix undefined array key `HTTP_USER_AGENT`

application/forms/ApiTransportForm.php
=> ApiTransportForm: Don't use text to create password elements

public/css/common.less
Remove comment or downtime: When you click the "Remove" button, the background of the button changes to icinga-blue with a red border (looks strange).
fixes #483
=> Use a red background on focus for remove buttons

library/Icingadb/Widget/ItemList/BaseHistoryListItem.php
An OK state is never a soft state, so if it's not desirable
to show OK as previous state, always show previous soft states :)
fixes #491
=> Always show the previous soft state in history list items

public/css/widget/view-mode-switcher.less
There were some issues with the `.view-mode-switcher` not being consistent with the rest of the controls.
This makes it more consistent, when overriding colors in themes.
related to [Icinga/icingaweb2/#4673](https://github.com/Icinga/icingaweb2/pull/4673)
and [Icinga/ipl-web/#67](https://github.com/Icinga/ipl-web/compare/bugfix/css-fix-theme-issues?expand=1)
=> view-mode-switcher: Optimize for theming

library/Icingadb/Widget/Detail/DowntimeDetail.php
Also fixes a theoretical error, as `createServiceLink`
returns a `FormattedString` which has no attributes.
=> DowntimeDetail: Don't register class `subject` twice

library/Icingadb/Model/Instance.php
In case of multiple responsible=y rows (crashed instance and running instance)
make sure to get the one with the latest heartbeat not to give a false positive "Icinga DB is not running" (other heartbeat expired).
refs Icinga/icingadb#424
=> Model\Instance: sort rows of equal responsibility by latest heartbeat

application/controllers/ServicesController.php, application/views/scripts/services/grid-flipped.phtml, application/views/scripts/services/grid.phtml
Ensures compatibility with Icinga/ipl-orm#52. Backwards compatibility is still the case.
=> services/grid: Cleanup column aliases

application/controllers/HistoryController.php, application/controllers/HostController.php, application/controllers/NotificationsController.php, library/Icingadb/Common/Auth.php, library/Icingadb/Compat/UrlMigrator.php, library/Icingadb/Model/Behavior/FlattenedObjectVars.php, library/Icingadb/Web/Control/SearchBar/ObjectSuggestions.php, library/Icingadb/Web/Controller.php, library/Icingadb/Widget/Detail/ObjectDetail.php
Ensures compatibility with https://github.com/Icinga/ipl-stdlib/pull/33. **Not** backwards compatible.
=> Adjust usages of `ipl\Stdlib\Filter::equal()` and `::unequal()`

library/Icingadb/Common/ObjectInspectionDetail.php, library/Icingadb/Hook/CustomVarRendererHook.php, library/Icingadb/Widget/Detail/CustomVarTable.php, library/Icingadb/Widget/Detail/HostInspectionDetail.php, library/Icingadb/Widget/Detail/ObjectDetail.php, library/Icingadb/Widget/Detail/ServiceInspectionDetail.php, library/Icingadb/Widget/Detail/UserDetail.php, library/Icingadb/Widget/Detail/UsergroupDetail.php, public/css/widget/custom-var-table.less
=> Custom variable rendering hooks

library/Icingadb/Widget/Detail/ObjectsDetail.php
Icingadb hosts are not showing the host state badges in the detail view upon multi-select. This fix solves the issue.
=> Show host badges in objects-detail for multi-selected hosts

library/Icingadb/Authentication/ObjectAuthorization.php
The `Sql::columns()` method doesn't override existing columns when calling this directly, because
at this point the ipl/orm query has already collected all selectable columns, which are not required
for this use case. A later call to the `columns()` method using the select base doesn't prevent all the
columns registered by the query from being selected.
=> Don't use `columns()` of ipl/sql to specify columns to be selected

library/Icingadb/Widget/Detail/PerfDataTable.php
This ensures that all perfdata which can't be visualized are rendered exactly in the
same order they are stored in the database after all vizualizable perfData are rendered.
fixes #562
=> Don't sort perfData which can't be visualized

doc/01-About.md
Our tooling for icinga.com/docs fails to parse this link properly.
=> Docs/About: Remove link to license

library/Icingadb/ProvidedHook/ApplicationState.php, library/Icingadb/ProvidedHook/RedisHealth.php
When icinga redis is down, icingadb also shut down after a few minutes.
In this case, the real cause of icingadb being down is that redis is down.
So we should check icinga redis status first.
=> ApplicationState: Check the availability of `IcingaRedis` first

public/css/widget/performance-data-table.less
Since the vertical scrolling must disabled upon clip, only `overflow-x` property is set to `auto`. Similar to `performance-data-table` class in monitoring module.
This fix disables the vertical scrolling in the `performance-data-table` when it overflows.
fixes #581
=> Change `overflow` property to `overflow-x` in `performance-data-table` class

library/Icingadb/Widget/ItemList/BaseCommentListItem.php
If the expiration time is set for a comment, we need to show the expire time. Use `ipl\Web\Widget\TimeUntil::class` for formatting and creating expiration time stamp.
If the expiration time is not set show creation time. In this case use `ipl\Web\Widget\TimeAgo::class` for formatting and creating creation time stamp.
fixes #578
=> Show expiration time of comments in the comments list if it is set

library/Icingadb/Common/ObjectInspectionDetail.php
Nowadays hGet returns null instead of false if there is no data available yet.
But since we are performing strict comparison on false, it won't enter the if branch anymore.
There is another Predis client method we use which is `hmGet`, but as usual it still returns only an array.
fixes #606
=> Don't strictly check whether `hGet` returns false

library/Icingadb/Util/PerfDataFormat.php
=> PerfDataFormat: Ensure not to use string values when formatting perfdata

library/Icingadb/Widget/ItemList/StateListItem.php, public/css/widget/state-change.less
`pending` state balls will be represented as hollowed state balls instead of solid state balls (ipl-web@3bccdd0da71a178fc0b10422275bfee8c4d3f4a4). Hence, `pending` state balls must behave similarly as `ok` or `up` upon change in state of the object.
Also, in case a downtime is scheduled for `pending` objects, their state balls must contain `plug` icon.
depends on icinga/ipl-web#90
=> Fix pending state balls

library/Icingadb/ProvidedHook/IcingaHealth.php
The warning state badges should be shown when notifications or active host/service checks are disabled.
fixes #608
=> Show warning health state badges

library/Icingadb/Util/PerfDataSet.php, library/Icingadb/Widget/Detail/PerfDataTable.php
At the moment we only render the sorted perfData in the object details, but when switching to
the detailed view mode the same perfData are rendered unsorted. This PR ensures that the perfData
are also sorted once after they have been successfully parsed.
=> Sort also pie charts in detailed view mode

application/controllers/MigrateController.php, library/Icingadb/Hook/ExtensionHook/ObjectDetailExtensionHook.php, library/Icingadb/Hook/ExtensionHook/ObjectsDetailExtensionHook.php, library/Icingadb/Hook/TabHook/HookActions.php, library/Icingadb/Widget/Detail/ObjectDetail.php
The deprecated hook `Icinga\Web\Hook` is replaced with `Icinga\Application\Hook` where ever  it is used.
=> Replace deprecated hook `Icinga\Web\Hook` with `Icinga\Application\Hook`

library/Icingadb/Model/Hostgroupsummary.php, library/Icingadb/Model/ServicegroupSummary.php
Previously:
* Base columns were identified as relation columns
* Base columns were not enriched (had no labels)
* Hostgroup columns were invalid in the servicegroupsummary and vice versa
=> Make group summaries work in the SearchBar

public/css/list/item-list.less
=> css: Prevent scrollbars to appear if icon images are large

library/Icingadb/Widget/ItemList/StateListItem.php
In case of handled hosts/services acknowledged state must be give priority over downtime and downtime
should be given priority over flapping. So the order for the handled state icons  must be
acknowledged, downtime or flapping respectively.
=> Change the order of handled state icons

library/Icingadb/Widget/Detail/ObjectDetail.php
=> Still load legacy hooks in object details if monitoring is just disabled

library/Icingadb/Widget/ItemList/HostListItemDetailed.php, library/Icingadb/Widget/ItemList/ServiceListItemDetailed.php
The `last_comment` relation is joined by the base query. This causes the underlying model to have nulled properties if the `last_comment_id` is set but the comment is not yet written to database.
closes #659
=> Avoid accessing non-existent last comment

library/Icingadb/Common/Database.php
=> Database: Only use `PDO::MYSQL_ATTR_INIT_COMMAND` for mysql connections

library/Icingadb/Widget/Detail/EventDetail.php
Not sure why this worked previously, but `DateTimeZone::__construct()` only accepts strings anyway :man_shrugging: 
fixes #667
=> EventDetail: Use `'UTC'` instead of `DateTimeZone::UTC`

application/forms/RedisConfigForm.php
=> RedisConfigForm: Properly store password of 2nd redis

library/Icingadb/Util/PerfData.php
'U' is neither a valid SI unit nor a valid prefix, so excluding it in the UOM part of the regex should not cause any issues.
The UOM regex now also accepts the `μ` prefix. Icinga normalizes values, but the regex seems to try to include them anyway.
If there is no numeric value, the pie chart can't show anything, so we test for that.
closes #700
=> Fix parsing unknown value in PerfData

library/Icingadb/Common/IcingaRedis.php
Fix Secondary Redis being ignored when the Primary Redis in inaccessible
fixes #715
=> Fix Redis HA

application/controllers/HistoryController.php, application/controllers/NotificationsController.php
fix #733
Bug exists since: https://github.com/Icinga/icingadb-web/pull/254
The `PaginationControl` always sets the offset. This must be reset when the page is reloaded.
=> `Pagination|History`: Reset query offset on page reload

doc/04-Security.md
`users`  and `usergroups` are the correct possible values instead of `contacts` and `contactgroups` for the Denylist `icingadb/denylist/routes`.
fix #692
=> Mention correct possible values for `icingadb/denylist/routes`

library/Icingadb/Widget/ItemList/BaseHistoryListItem.php
If the downtime ends normally it must be displayed `Downtime ended` instead of `Downtime cancelled`.
fix #691
=> Fix confusing `Downtime cancelled` header in event history list

application/controllers/HostsController.php, application/controllers/ServicesController.php
=> Severity sort must also sort objects by `last_state_change` in descending

application/controllers/ServicesController.php, application/views/scripts/joystickPagination-icingadb.phtml, application/views/scripts/services/grid-flipped.phtml, application/views/scripts/services/grid.phtml, library/Icingadb/Data/PivotTable.php
The pagination parameters must be unset when the limit parameter is `0,0` and the service grid for all the hosts and services must be displayed.
fixes #714
=> Unset pagination parameters for service grid when `limit=0,0`

application/forms/Command/Object/ProcessCheckResultForm.php, application/forms/Command/Object/ScheduleHostDowntimeForm.php
refs https://github.com/Icinga/ipl-html/pull/89
=> Ipl-html/SelectElement: Use `options` attr instead of `multiOptions`

library/Icingadb/Authentication/ObjectAuthorization.php
=> ObjectAuthorization: Quote rolename containing `dot (.)` correctly

library/Icingadb/Model/CustomvarFlat.php, library/Icingadb/Widget/Detail/ObjectDetail.php
=> Fix that variable names with dots are interpreted as paths

library/Icingadb/Data/CsvResultSet.php, library/Icingadb/Data/JsonResultSet.php
Remove parameter type for second argument (`$value`) in `CsvResultSet::formatValue` and `JsonResultSet::formatValue`. Also add date time formatting for `$value` parameter in case it is an instance of `DateTime` object.
fixes #782
=> Fix key-value formatting for json and csv result set

library/Icingadb/Common/Auth.php, library/Icingadb/Redis/VolatileStateResults.php
Users who do not have permission to see the object's `Source` tab, must be restricted from accessing the object's `state.check_commandline` column.
fixes [ref/IP/44766](https://rt.icinga.com/Ticket/Display.html?id=44766)
=> Avoid leakage of `state.check_commandline` to restricted users

application/controllers/MigrateController.php, library/Icingadb/Compat/UrlMigrator.php
=> Fix migration false positives

public/js/migrate.js
The latter is now always decoded, since #787
=> migrate.js: Decode urls prior comparison with migration results

library/Icingadb/Widget/Detail/CheckStatistics.php
=> CheckStatistics: Don't simulate running checks if they're overdue

library/Icingadb/Common/HostStates.php, library/Icingadb/Common/StateBadges.php, library/Icingadb/Model/Hostgroupsummary.php, library/Icingadb/Model/HoststateSummary.php, library/Icingadb/Model/ServicegroupSummary.php, library/Icingadb/Model/ServicestateSummary.php, library/Icingadb/Model/State.php, library/Icingadb/Widget/Detail/CheckStatistics.php, library/Icingadb/Widget/HostSummaryDonut.php, library/Icingadb/Widget/ItemList/HostDetailHeader.php, library/Icingadb/Widget/ItemList/ServiceDetailHeader.php, library/Icingadb/Widget/ItemList/StateListItem.php, library/Icingadb/Widget/ItemTable/HostgroupGridCell.php, library/Icingadb/Widget/ItemTable/ServicegroupGridCell.php, public/css/mixin/progress-bar.less, test/php/library/Icingadb/Common/StateBadgesTest.php
=> Fix that unreachable hosts and services are not shown as such

application/controllers/HostController.php, application/controllers/ServiceController.php, library/Icingadb/Command/Object/ObjectsCommand.php
=> Fix broken source tab

library/Icingadb/Common/BaseItemTable.php, library/Icingadb/Widget/ItemTable/HostgroupTable.php, library/Icingadb/Widget/ItemTable/ServicegroupTable.php, public/css/common.less
This elevates the layout `table-layout`, previously introduced exclusively for host and service group
tables, to the standard layout used for item tables.
fixes #814
=> BaseItemTable: Introduce layout modes

application/controllers/HistoryController.php, application/controllers/HostController.php, application/controllers/ServiceController.php, library/Icingadb/Model/History.php
=> History: Sort also by type by default

public/js/action-list.js
=> action-list.js: Use `getAttribute` to get `href`

library/Icingadb/Common/ObjectInspectionDetail.php
=> ObjectInspectionDetail: Render 'n. a.' if $command is empty

application/controllers/CommandTransportController.php, library/Icingadb/Widget/Detail/CheckStatistics.php, library/Icingadb/Widget/Detail/DowntimeCard.php, public/css/common.less
- https://github.com/Icinga/ipl-web/pull/167
- https://github.com/Icinga/icingaweb2/pull/5059
=>  Apply `csp` to inline css style

application/forms/Command/CommandForm.php, library/Icingadb/Common/CommandActions.php
The routes used are the same that are used when issuing commands on multiple objects (bulk actions). So the filter that's used in the examples can be any other filter as well. Input data must be provided as `multipart/form-data`.
They respond with the JSON format provided by Icinga Web and are only accessible for non-XHR clients.
```
curl -H "Accept: application/json" -u icingaadmin:icinga "http://localhost/icingaweb2/icingadb/hosts/add-comment?host.name=docker-master" -F "comment=kaput" -F "expire_time=2023-09-05T20:00:00" -F "expire=y" -v
*   Trying 127.0.0.1:80...
* Connected to localhost (127.0.0.1) port 80 (#0)
* Server auth using Basic with user 'icingaadmin'
> POST /icingaweb2/icingadb/api/v1/hosts/add-comment?host.name=docker-master HTTP/1.1
> Host: localhost
> Authorization: …
```
=> Make command actions easier to use with curl

library/Icingadb/Data/CsvResultSet.php, library/Icingadb/Data/JsonResultSet.php, library/Icingadb/Redis/VolatileStateResults.php, phpstan-baseline.neon
=> Fix redis states not applied to exports

application/controllers/CommentsController.php, application/controllers/DowntimesController.php, application/controllers/HistoryController.php, application/controllers/HostsController.php, application/controllers/MigrateController.php, application/controllers/NotificationsController.php, application/controllers/ServicesController.php, library/Icingadb/Common/StateBadges.php, library/Icingadb/Compat/UrlMigrator.php, library/Icingadb/Web/Controller.php, library/Icingadb/Widget/Detail/CommentDetail.php, library/Icingadb/Widget/Detail/DowntimeDetail.php, library/Icingadb/Widget/Detail/HostStatistics.php, library/Icingadb/Widget/Detail/MultiselectQuickActions.php, library/Icingadb/Widget/Detail/ObjectsDetail.php, library/Icingadb/Widget/Detail/ServiceStatistics.php, library/Icingadb/Widget/HostSummaryDonut.php, library/Icingadb/Widget/ItemTable/HostgroupGridCell.php, library/Icingadb/Widget/ItemTable/ServicegroupGridCell.php, library/Icingadb/Widget/ServiceSummaryDonut.php, phpstan-baseline.neon, test/php/library/Icingadb/Common/StateBadgesTest.php
requires https://github.com/Icinga/ipl-web/pull/195 and https://github.com/Icinga/ipl-web/pull/203
=> Utilize `ipl\Web\Url::setFilter()` where applicable

public/js/action-list.js
Suspending the autorefresh is only required while the user is actively choosing multiple list items.
fixes #879
=> Fix broken detail view refreshes

application/controllers/MigrateController.php, library/Icingadb/Compat/UrlMigrator.php
=> migrate: Properly override url params

library/Icingadb/Common/IcingaRedis.php
=> IcingaRedis: Don't throw in method `isUnavailable`

application/controllers/MigrateController.php, public/js/migrate.js
=> Fix that the migration widget doesn't suggest updated search urls if the sort column/direction is changed

library/Icingadb/Common/Macros.php, library/Icingadb/Widget/Detail/ObjectDetail.php
=> Transform compat `action` & `notes` url macros automatically

library/Icingadb/Model/CustomvarFlat.php, test/php/library/Icingadb/Model/CustomvarFlatTest.php
=> Don't use values from `customvar` table for all custom vars

library/Icingadb/Common/Macros.php, test/php/library/Icingadb/Common/MacrosTest.php
=> Fix that some macros break the host detail

library/Icingadb/Widget/Detail/CheckStatistics.php
A too small check interval can let the last and next check appear to be at the same time due to rounding to milliseconds. Their difference is 0 which shall not be used for division.
```
object Host "656" {
check_command = "dummy"
vars.dummy_state = 2
check_interval = 1ms
retry_interval = 1ms
max_check_attempts = 1000
}
```
```
Division by zero
#0 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Widget/Detail/CheckStatistics.php(126): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}()
#1 /usr/share/icinga-php/ipl/vendor/ipl/web/src/Common/Card.php(24): Icinga\Module\Icingadb\Widget\Detail\CheckStatistics->assembleBody()
#2 /usr/share/icinga-php/ipl/vendor/ipl/web/src/Common/Card.php(55): ipl\Web\Common\Card->createBody()
#3 …
```
=> CheckStatistics#assembleBody(): avoid divisions by 0

public/js/action-list.js
@sukhwinder33445 I've changed the refresh suspension quite a bit, please re-test if the key navigation still behaves like you intended.
fixes #696
=> Fix that the dashboard loses selection, again

application/controllers/HostController.php
=> host/services: Make sure severity sort orders the same as anywhere else

library/Icingadb/Widget/Detail/CheckStatistics.php
..if both active and passive checks are disabled.
fixes #930
=> CheckStatistics: Don't attempt to visualize next checks..

application/controllers/MigrateController.php
=> migrate/search-url: Prevent further false-positives

doc/03-Configuration.md, doc/10-Migration.md
This adds a listing of the possible settings for the module in the configuration files.
It is quite similar to the monitoring module, but wasn't documented for this one.
=> Add document for the configuration of the IcingaDB-Modul

library/Icingadb/Compat/UrlMigrator.php
=> Fix incorrect url migrations

library/Icingadb/Common/Macros.php, phpstan.neon
=> Macros: Log the object where a macro is not found

library/Icingadb/Web/Controller.php
=> Controller: Serve JSON if accepted

doc/02-Installation.md.d/From-Source.md, library/Icingadb/Model/Behavior/FlattenedObjectVars.php, library/Icingadb/Model/CustomvarFlat.php, module.info, phpstan-baseline-standard.neon, test/php/library/Icingadb/Model/Behavior/FlattenedObjectVarsTest.php
fixes #865
requires https://github.com/Icinga/ipl-orm/pull/132
=> Transform custom variable filters as late as possible

library/Icingadb/Data/CsvResultSet.php, library/Icingadb/Data/CsvResultSetUtils.php, library/Icingadb/Data/JsonResultSet.php, library/Icingadb/Data/JsonResultSetUtils.php, library/Icingadb/Data/VolatileCsvResults.php, library/Icingadb/Data/VolatileJsonResults.php, library/Icingadb/Web/Controller.php, phpstan-baseline-7x.neon, phpstan-baseline-8x.neon, phpstan-baseline-standard.neon
=> Fix history exports

library/Icingadb/Model/Behavior/FlattenedObjectVars.php, test/php/library/Icingadb/Model/Behavior/FlattenedObjectVarsTest.php
fixes #1001
requires https://github.com/Icinga/ipl-orm/pull/133
=> Fix that custom variables with dots in their name are broken

application/forms/Command/CommandForm.php, application/forms/Command/Instance/ToggleInstanceFeaturesForm.php, application/forms/Command/Object/AcknowledgeProblemForm.php, application/forms/Command/Object/AddCommentForm.php, application/forms/Command/Object/CheckNowForm.php, application/forms/Command/Object/DeleteCommentForm.php, application/forms/Command/Object/DeleteDowntimeForm.php, application/forms/Command/Object/ProcessCheckResultForm.php, application/forms/Command/Object/RemoveAcknowledgementForm.php, application/forms/Command/Object/ScheduleCheckForm.php, application/forms/Command/Object/ScheduleHostDowntimeForm.php, application/forms/Command/Object/ScheduleServiceDowntimeForm.php, application/forms/Command/Object/SendCustomNotificationForm.php, application/forms/Command/Object/ToggleObjectFeaturesForm.php, library/Icingadb/Command/Object/ObjectsCommand.php, library/Icingadb/Common/CommandActions.php, library/Icingadb/Widget/Detail/MultiselectQuickActions.php, phpstan-baseline-7x.neon, phpstan-baseline-8x.neon, phpstan-baseline-standard.neon, test/php/Lib/StrikingCommandTransport.php, test/php/library/Icingadb/Command/Transport/CommandTransportTest.php
=> Fix broken command transport fallback handling

library/Icingadb/Model/Hostgroupsummary.php, library/Icingadb/Model/ServicegroupSummary.php
fixes #954
this is is a follow-up from #994
=> Fix missing `name_ci` filter during global group search

library/Icingadb/Data/JsonResultSetUtils.php
fixes https://github.com/Icinga/icingadb-web/issues/1014
=> JsonResultSetUtils: When query offset is null, Use 0 as default

library/Icingadb/Util/PluginOutput.php, phpstan-baseline-7x.neon, phpstan-baseline-8x.neon, phpstan-baseline-standard.neon, test/php/library/Icingadb/Util/PluginOutputTest.php
=> PluginOutput::render():  Return correctly cut off output

doc/03-Configuration.md, library/Icingadb/Widget/Detail/EventDetail.php, library/Icingadb/Widget/Detail/ObjectDetail.php, phpstan-baseline-standard.neon
=> Configurable output limit

library/Icingadb/Hook/ActionsHook/ObjectActionsHook.php, library/Icingadb/Hook/CustomVarRendererHook.php, library/Icingadb/Hook/ExtensionHook/ObjectDetailExtensionHook.php, library/Icingadb/Hook/ExtensionHook/ObjectsDetailExtensionHook.php, library/Icingadb/Hook/PluginOutputHook.php, library/Icingadb/Hook/TabHook/HookActions.php, library/Icingadb/Widget/Detail/ObjectDetail.php
Hooks shouldn't be able to fatally end execution.
=> Catch `\Throwable` when utilizing hooks

library/Icingadb/Model/DependencyEdge.php, library/Icingadb/Model/DependencyNode.php, library/Icingadb/Model/Host.php, library/Icingadb/Model/RedundancyGroup.php, library/Icingadb/Model/Service.php
The previous relations didn't work as expected.
Now, filtering with `child.host.name` or
`parent.service.name` works fine.
=> db: Cleanup parent/child relations in matching models

library/Icingadb/Common/Icons.php, library/Icingadb/Model/Host.php, library/Icingadb/Model/HostState.php, library/Icingadb/Model/Service.php, library/Icingadb/Model/ServiceState.php, library/Icingadb/Model/State.php, library/Icingadb/Widget/ItemList/StateListItem.php, public/css/common.less
=> Indicate the number of affected children by a particular parent

application/controllers/ServiceController.php, library/Icingadb/Common/StateBadges.php, library/Icingadb/Model/Behavior/HasProblematicParent.php, library/Icingadb/Model/RedundancyGroupState.php, library/Icingadb/Model/RedundancyGroupSummary.php, library/Icingadb/Model/Service.php, library/Icingadb/Model/UnreachableParent.php, library/Icingadb/Redis/VolatileStateResults.php, library/Icingadb/Widget/DependencyNodeStateBadges.php, library/Icingadb/Widget/DependencyNodeStatistics.php, library/Icingadb/Widget/Detail/HostDetail.php, library/Icingadb/Widget/Detail/ObjectDetail.php, library/Icingadb/Widget/Detail/ServiceDetail.php, library/Icingadb/Widget/ItemList/DependencyNodeList.php, library/Icingadb/Widget/ItemList/RedundancyGroupListItem.php, library/Icingadb/Widget/ItemList/StateListItem.php, public/css/common.less, public/css/list/redundancy-group-list-item.less, public/css/widget/dependency-node-state-badges.less, test/php/library/Icingadb/Common/StateBadgesTest.php
ref #1050
blocked by: #1055
blocked by: Icinga/ipl-web#231,  Icinga/ipl-web#234
=> Show root problem list for objects with problem and are part of dependency

library/Icingadb/Widget/Detail/HostDetail.php, library/Icingadb/Widget/Detail/ObjectDetail.php, library/Icingadb/Widget/Detail/ServiceDetail.php
=> Show affected objects in the object detail for failed dependencies

application/controllers/RedundancygroupController.php, library/Icingadb/Authentication/ObjectAuthorization.php, library/Icingadb/Data/DependencyNodes.php, library/Icingadb/Hook/ExtensionHook/ObjectDetailExtensionHook.php, library/Icingadb/Hook/RedundancyGroupDetailExtensionHook.php, library/Icingadb/Model/DependencyNode.php, library/Icingadb/Model/RedundancyGroup.php, library/Icingadb/Model/RedundancyGroupSummary.php, library/Icingadb/Model/UnreachableParent.php, library/Icingadb/Widget/Detail/MultiselectQuickActions.php, library/Icingadb/Widget/Detail/ObjectHeader.php, library/Icingadb/Widget/Detail/RedundancyGroupDetail.php, library/Icingadb/Widget/Detail/RedundancyGroupHeader.php, library/Icingadb/Widget/ItemList/DependencyNodeList.php, library/Icingadb/Widget/ItemList/RedundancyGroupListItem.php, public/css/widget/object-header.less
=> Add redundancy group detail view

doc/05-Upgrading.md, library/Icingadb/Common/Backend.php, library/Icingadb/Common/Database.php, library/Icingadb/Common/IcingaRedis.php, library/Icingadb/Common/ObjectInspectionDetail.php, library/Icingadb/Model/Schema.php, library/Icingadb/Redis/VolatileStateResults.php, test/php/library/Icingadb/Model/Behavior/FlattenedObjectVarsTest.php
Required for an upcoming change. Though, I wanted to change this already a long time ago.
There's absolutely no need to have several open connections to the same database. Which was the case before, since the connection was established for each user (class) of the `Database` trait.
But with PDO, queries are by default all serially processed. Only for MySQL it is possible to change this, by [disabling query buffering](https://www.php.net/manual/en/mysqlinfo.concepts.buffering.php).
But Icinga DB Web is incompatible anyway, with disabled query buffering, and so changing this to a singleton is fine in my opinion.
I've deliberately kept the `Database` trait, to not update all usages of it. In case only the connection is required, the trait still has its use.
=> Use singleton for db and redis connections

application/controllers/ServiceController.php, library/Icingadb/Model/Host.php, library/Icingadb/Model/HostState.php, library/Icingadb/Model/Service.php, library/Icingadb/Model/ServiceState.php, library/Icingadb/Model/State.php, library/Icingadb/Widget/Detail/ObjectDetail.php, library/Icingadb/Widget/ItemList/StateListItem.php
=> Keep compatibility with Icinga DB v5

application/controllers/RedundancygroupController.php
resolves https://github.com/Icinga/icingadb-web/issues/1109
=> RedundancyGroupController: Add `CSV/JSON` export options

application/controllers/ServiceController.php, library/Icingadb/Common/Backend.php, library/Icingadb/Model/Host.php, library/Icingadb/Model/HostState.php, library/Icingadb/Model/Service.php, library/Icingadb/Model/ServiceState.php, library/Icingadb/Model/State.php, library/Icingadb/Widget/Detail/ObjectDetail.php
ref https://github.com/Icinga/icingadb-web/pull/1114
=> Keep compatibility with Icinga DB v6

application/controllers/RedundancygroupController.php, library/Icingadb/Model/Hostgroup.php, library/Icingadb/Model/Servicegroup.php, library/Icingadb/Web/Control/SearchBar/ObjectSuggestions.php
The `ObjectSuggestions` instance with `DependencyNode` as the model can only retrieve custom variables for `Host, Service, Hostgroup and Servicegroup`. Other relations are not defined and lead to an error.
=> ObjectSuggestions: Make CustomVar suggestion sources adjustable

library/Icingadb/Web/Control/SearchBar/ObjectSuggestions.php
Blocked by: https://github.com/Icinga/icingadb-web/pull/1100
- The basefilter may contain relations, that are not know to `CustomvarFlat`, which can leads to errors. 
For example: `RedundancygroupController:completeAction`'s base filter (`(parent|child).redundancy_group.id)`) is not known to `CustomvarFlat`.
=> ObjectSuggestions: Don't apply base filter to $customVars query

application/controllers/HostController.php, application/controllers/HostgroupsController.php, application/controllers/HostsController.php, application/controllers/ServicegroupsController.php, application/controllers/ServicesController.php
resolves #1096
requires https://github.com/Icinga/ipl-web/pull/241
=> Use severity as default sort

application/clicommands/MigrateCommand.php, application/controllers/ContactController.php, application/controllers/ContactgroupController.php, application/controllers/ContactgroupsController.php, application/controllers/ContactsController.php, application/controllers/UserController.php, application/controllers/UsergroupController.php, application/controllers/UsergroupsController.php, application/controllers/UsersController.php, configuration.php, doc/04-Security.md, doc/10-Migration.md, library/Icingadb/Common/Auth.php, library/Icingadb/Common/Links.php, library/Icingadb/Compat/UrlMigrator.php, library/Icingadb/Model/NotificationHistory.php, library/Icingadb/Model/Usergroup.php, library/Icingadb/Web/Control/SearchBar/ObjectSuggestions.php, library/Icingadb/Widget/Detail/EventDetail.php, library/Icingadb/Widget/Detail/ObjectDetail.php, library/Icingadb/Widget/Detail/UsergroupDetail.php, library/Icingadb/Widget/ItemList/ObjectList.php, test/php/application/clicommands/MigrateCommandTest.php
This ensures that the UI will stop using the term *user* in favor of *contact* and the term *usergroup* in favor of *contactgroup*.
Routes and denylists will also change accordingly.
What does not change, are database table names. While it would be certainly possible, changing relation names is a breaking change I'd like to avoid. It would break any restriction on `<type>.user.name` and `<type>.usergroup.name`.
@flourish86 Please ensure the UI doesn't use the old terms anywhere.
@sukhwinder33445 Please ensure I did not forget anything related to routes and denylists.
closes #944
=> Rename users and usergroups to contacts and contactgroups

application/controllers/HostController.php, application/controllers/ServiceController.php
This change was missing in the https://github.com/Icinga/icingadb-web/pull/734
fixes https://github.com/Icinga/icingadb-web/issues/1164
=> (Host|Service)Controller: Reset the query offset for LoadMore list

library/Icingadb/Hook/CustomVarRendererHook.php
=> CustomVarRendererHook: Log an exception's message and location

library/Icingadb/Widget/Detail/MultiselectQuickActions.php, library/Icingadb/Widget/Detail/QuickActions.php
fixes https://github.com/Icinga/icingadb-web/issues/1105
=> QuickActions: Hide `Process check` and `Notification` button when feature is disabled

library/Icingadb/Common/Macros.php
=> Macros: Add missing support for `DateTime` type macro

library/Icingadb/Web/Control/SearchBar/ObjectSuggestions.php
Currently, the limit is globally set to 50, hence the short custom variable names which overlaps with most of the column names will not be suggested and instead only column names will be suggested. To prevent this the default limit is split in half and adjusted dynamically based on available suggestions.
resolves #1094
=> ObjectSuggestion: Dynamically adjust columns and custom var suggestion limits

application/controllers/CommentController.php, application/controllers/CommentsController.php, application/controllers/DowntimeController.php, application/controllers/DowntimesController.php, application/forms/Command/Object/DeleteCommentForm.php, application/forms/Command/Object/DeleteDowntimeForm.php, doc/09-Automation.md, library/Icingadb/Common/CommandActions.php, library/Icingadb/Widget/Detail/CommentDetail.php, library/Icingadb/Widget/Detail/DowntimeDetail.php
=> Add missing support for automated removal of downtimes and comments

application/forms/Command/Object/DeleteCommentForm.php, application/forms/Command/Object/DeleteDowntimeForm.php
=> `Delete(Downtime|Comment)Form`: Fix the incorrect success message

library/Icingadb/Common/ObjectInspectionDetail.php
=> ObjectInspectionDetail: Show host/service templates

library/Icingadb/Model/Host.php, library/Icingadb/Model/Service.php
=> Models: Register the `to 1` relations first to display them first in the search suggestions

library/Icingadb/Widget/ItemList/ObjectList.php
caused by: https://github.com/Icinga/icingadb-web/pull/1141
=> ObjectList: Don't add non-supported multiselect url to member/children list items of RedundancyGroup

library/Icingadb/Web/Control/SearchBar/ObjectSuggestions.php
Show custom variable suggestions only if the column suggestions have not consumed all the slots (50).
fixes #1206
=> ObjectSuggestions: Prioritze Column suggestions and best suggestions

library/Icingadb/ProvidedHook/IcingaHealth.php, library/Icingadb/Widget/Health.php
The old redis schema is incompatible with v1.2.0 hence the health check should report a critical incident instead.
Also updates the health view to show a proper message.
=> IcingaHealth: Switch to critical in case Icinga DB is too old

library/Icingadb/Common/Auth.php
=> Auth: Apply filter/hosts and filter/services to dependency queries
